# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 07:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doodleDO', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='meeting_name',
            field=models.CharField(default='bla', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meeting',
            name='meeting_votes_required',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_date',
            field=models.DateField(blank=True, null=True, verbose_name='meeting date'),
        ),
    ]
