# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 07:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doodleDO', '0002_auto_20171005_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='meeting_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doodleDO.Room'),
        ),
    ]
