# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 15:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doodleDO', '0003_auto_20171005_0913'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_date', models.DateField(verbose_name='date vote')),
                ('date_meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doodleDO.Meeting')),
            ],
        ),
        migrations.AlterField(
            model_name='vote',
            name='vote_date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doodleDO.MeetingDate'),
        ),
    ]
